services:
  test_service.postgres:
    image: postgres:16
    hostname: test_service.postgres
    container_name: test_service.postgres
    ports:
    - ${POSTGRES_PORT}:5432
    volumes:
    - pgdata:/var/lib/postgresql/data
    env_file:
    - .env
  test_service.backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - ${APP_PORT}:8080
    env_file:
    - ./.env
volumes:
  pgdata:
